spring:
  h2:
    console:
      enabled: true

  datasource:
    username: root
    url: jdbc:h2:mem:testdb
  security:
    user:
      name: user
      password: password

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics"]
  metrics:
    web:
      server:
        auto-time-requests: false
